version: "3.9"  # optional since v1.27.0
services:
  bitwarden:
    image: vaultwarden/server:1.24.0
    ports:
      - "13883:80"
    volumes:
      - /data/bitwarden:/data
    environment:
      - SIGNUPS_ALLOWED=false